### PR TITLE
Exclude the macOS preserved '/usr' from java home list

### LINKED ISSUE #15: [macOS] Detect /usr as a wrong java home
See https://github.com/redhat-developer/vscode-java/issues/3287#issuecomment-1717525516, on macOS it detects `/usr` as java home by mistake.

> npm i jdk-utils && npx jdk-utils

```added 1 package, and audited 2 packages in 1s

found 0 vulnerabilities
Listing JDKs: 76.725ms
Found:  4
[
  {
    homedir: '/usr/local/Cellar/openjdk@17/17.0.8.1/libexec/openjdk.jdk/Contents/Home',
    hasJavac: true,
    version: { java_version: '17.0.8.1', major: 17 }
  },
  {
    homedir: '/usr/local/Cellar/openjdk@11/11.0.20.1/libexec/openjdk.jdk/Contents/Home',
    hasJavac: true,
    version: { java_version: '11.0.20.1', major: 11 }
  },
  {
    homedir: '/usr/local/Cellar/openjdk/20.0.2/libexec/openjdk.jdk/Contents/Home',
    hasJavac: true,
    version: { java_version: '20.0.2', major: 20 }
  },
  {
    homedir: '/usr',
    isInPathEnv: true,
    hasJavac: true,
    version: { java_version: '17.0.8.1', major: 17 }
  }
]
```

### PR DESCRIPTION
**Pull request by testforstephen**
Fixes #15

### CODE REVIEW

File: src/from/envs.ts [hunk 1]
```diff
@@ -13,7 +17,13 @@ export async function candidatesFromPath(): Promise<string[]> {
          * Fix for https://github.com/Eskibear/node-jdk-utils/issues/2
          * Homebrew creates symbolic links for each binary instead of folder.
          */
-        const homeDirs = await Promise.all(jdkBinFolderFromPath.map(p => getRealHome(path.dirname(p))));
+        const homeDirs = (await Promise.all(jdkBinFolderFromPath.map(p => getRealHome(path.dirname(p))))).filter(homeDir => {
+            /**
+             * Fix for https://github.com/Eskibear/node-jdk-utils/issues/15
+             * /usr/bin/java is a preserved shortcut program on macOS, which is not a real java home.
+             */
+            return homeDir && (!isMac || !EXCLUSIONS_ON_MAC.has(homeDir));
```
Comment (Eskibear) [inline src/from/envs.ts]: `!(isMac && EXCLUSIONS_ON_MAC.has(homeDir))` might be more human-readable.

**Review by Eskibear — APPROVED** [review]
LGTM
